
# auto generated by fish-lsp
complete -c fzf-history-search -s h -l help -d 'show help'
complete -c fzf-history-search -s c -l copy -d 'copy selected commands to clipboard'
complete -c fzf-history-search -l no-copy -d 'do not copy selected commands to clipboard'
complete -c fzf-history-search -l copy-only -d 'only copy selected commands to clipboard'
complete -c fzf-history-search -s i -l insert -d 'insert selected commands into command line'
complete -c fzf-history-search -s r -l replace -d 'replace command line with selected commands'
