.TH "FISH\-LSP" "1" "August 2025" "1.0.11-pre.12" "fish-lsp"
.SH "NAME"
\fBfish-lsp\fR \- A language server for the fish shell
.SH SYNOPSIS
.P
\fBfish\-lsp [OPTIONS]\fP
.br
\fBfish\-lsp [SUBCOMMAND] [OPTIONS]\fP
.SH DESCRIPTION
.P
\fBfish\-lsp\fP is a language server for the fish shell\. It provides IDE\-like features for fish shell scripts, such as syntax checking, linting, and auto\-completion\.
.P
It requires a language client that supports the Language Server Protocol (LSP)\.
.P
Some common language clients include: the builtin API for \fBnvim\fP (v0\.9+), lsp\-mode for \fBemacs\fP, or the fish\-lsp extension for \fBVSCode\fP\|\.
.P
Documentation below shows usage of the \fBfish\-lsp\fP command, including its subcommands and options\.
.SH OPTIONS
.P
\fB\-v\fP or \fB\-\-version\fP           Show version information and exit\.
.br
\fB\-h\fP or \fB\-\-help\fP              Show help message and exit\.
.br
\fB\-\-help\-all\fP                Show all the help information
.br
\fB\-\-help\-short\fP              Show shortened help message
.br
\fB\-\-help\-man\fP                Show manpage output
.SH SUBCOMMANDS
.SS \fBstart\fP
.P
Start the language server\.
.P
\fB\-\-enable\fP                  enable the language server features
.br
\fB\-\-disable\fP                 disable the language server features
.br
\fB\-\-dump\fP                    dump the json output of the language server features enabled after startup
.br
\fB\-\-stdio\fP                   use stdin/stdout for communication (default)
.br
\fB\-\-node\-ipc\fP                use node IPC for communication
.br
\fB\-\-socket <port>\fP           use TCP socket for communication
.br
\fB\-\-memory\-limit <mb>\fP       set memory usage limit in MB
.br
\fB\-\-max\-files <number>\fP      override the maximum number of files to analyze
.SS \fBenv\fP
.P
show the environment variables available to the lsp
.P
\fB\-c\fP or \fB\-\-create\fP            create the environment variable
.br
\fB\-s\fP or \fB\-\-show\fP              show the environment variables
.br
\fB\-\-show\-default\fP            show the default values for fish\-lsp env variables
.br
\fB\-\-only <VAR>\fP              only include the specified environment variables in the output
.br
\fB\-\-no\-global\fP               don't use global scope when generating environment variables
.br
\fB\-\-no\-local\fP                don't use local scope when generating environment variables
.br
\fB\-\-no\-export\fP               don't use export flag when generating environment variables
.br
\fB\-\-no\-comments\fP             skip outputting comments
.br
\fB\-\-confd\fP                   output for redirecting to conf\.d/fish\-lsp\.fish
.SS \fBinfo\fP
.P
show the build info of fish\-lsp
.P
\fB\-\-bin\fP                     show the path of the fish\-lsp executable
.br
\fB\-\-path\fP                    show the path of the entire fish\-lsp installation
.br
\fB\-\-build\-time\fP              show the path of the entire fish\-lsp repo
.br
\fB\-\-build\-type\fP              show the build type of the command
.br
\fB\-\-lsp\-version\fP             show the lsp version
.br
\fB\-\-capabilities\fP            show the lsp capabilities
.br
\fB\-\-man\-file\fP                show the man file path
.br
\fB\-\-log\-file\fP                show the log file path
.br
\fB\-\-show\fP                    show the man/log file contents (needs to be paired with \fB\-\-log\-file\fP or \fB\-\-man\-file\fP)
.br
\fB\-\-extra\fP                   show debugging server info (capabilities, paths, version, etc\.)
.br
\fB\-\-verbose\fP                 show debugging server info (capabilities, paths, version, etc\.)
.br
\fB\-\-check\-health\fP            run diagnostics and report health status
.br
\fB\-\-health\-check\fP            run diagnostics and report health status
.br
\fB\-\-time\-startup\fP            time the startup of the fish\-lsp executable
.br
\fB\-\-time\-only\fP               show brief summary of the startup timing
.br
\fB\-\-use\-workspace <PATH>\fP    use the workspace at the specified directory path when \fBfish\-lsp info \-\-time\-startup\fP is used
.br
\fB\-\-no\-warning\fP              disable message in the \fBfish\-lsp info \-\-time\-startup\fP output
.br
\fB\-\-dump\-parse\-tree <FILE>\fP  show the tree\-sitter AST for the specified file
.br
\fB\-\-no\-color\fP                disable color output in the \fBfish\-lsp info \-\-dump\-file\-tree\fP output
.SS \fBurl\fP
.P
show a helpful url related to the fish\-lsp
.P
\fB\-\-repo\fP or \fB\-\-git\fP           show the github repo
.br
\fB\-\-npm\fP                     show the npm package url
.br
\fB\-\-homepage\fP                show the homepage
.br
\fB\-\-contributions\fP           show the contributions url
.br
\fB\-\-wiki\fP                    show the github wiki
.br
\fB\-\-issues\fP or \fB\-\-report\fP      show the issues page
.br
\fB\-\-discussions\fP             show the discussions page
.br
\fB\-\-clients\-repo\fP            show the clients configuration repo
.br
\fB\-\-sources\fP                 show a list of helpful sources
.SS \fBcomplete\fP
.P
Provide completions for the \fBfish\-lsp\fP
.P
\fB\-\-names\fP                   show the feature names of the completions
.br
\fB\-\-toggles\fP                 show the feature names of the completions
.br
\fB\-\-fish\fP                    show fish script
.br
\fB\-\-features\fP                show features
.br
\fB\-\-env\-variables\fP           show env variable completions
.br
\fB\-\-env\-variable\-names\fP      show env variable names
.br
\fB\-\-names\-with\-summary\fP      show the names with the summary for the completions
.SH EXAMPLES

.RS 1
.IP \(bu 2
Start the \fBfish\-lsp\fP language server, with the default configuration:
.RS 2
.nf
>_ fish\-lsp start
.fi
.RE
.IP \(bu 2
Show the path to the \fBfish\-lsp\fP language server binary:
.RS 2
.nf
>_ fish\-lsp complete > ~/\.config/fish/completions/fish\-lsp\.fish
.fi
.RE
.IP \(bu 2
Debug the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp start \-\-dump
.fi
.RE
.IP \(bu 2
Show information about the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp info 
.fi
.RE
.IP \(bu 2
Show all the available information about the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp info \-\-verbose
.fi
.RE
.IP \(bu 2
Show startup timing information for the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp info \-\-time\-startup
.fi
.RE
.IP \(bu 2
Show startup timing information for the \fBfish\-lsp\fP language server for a specific workspace:
.RS 2
.nf
>_ fish\-lsp info \-\-time\-startup \-\-use\-workspace ~/\.config/fish \-\-no\-warning
.fi
.RE
.IP \(bu 2
Preform a health check on the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp info \-\-check\-health
.fi
.RE
.IP \(bu 2
Show the environment variables available to the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp env \-\-show
.fi
.RE
.IP \(bu 2
Show the default values for specific environment variables used by the \fBfish\-lsp\fP language server:
.RS 2
.nf
>_ fish\-lsp env \-\-show\-default \-\-only fish_lsp_all_indexed_paths,fish_lsp_max_background_files \-\-no\-comments
.fi
.RE
.IP \(bu 2
Get sources related to the \fBfish\-lsp\fP language server's development:
.RS 2
.nf
>_ fish\-lsp url \-\-sources
.fi
.RE

.RE
.SH SEE ALSO

.RS 1
.IP \(bu 2
\fBwebsite:\fR \fIhttps://fish-lsp.dev/\fR
.IP \(bu 2
\fBrepo:\fR \fIhttps://github.com/ndonfris/fish-lsp\fR
.IP \(bu 2
\fBfish website:\fR \fIhttps://fishshell.com/\fR

.RE
.SH AUTHOR

.RS 1
.IP \(bu 2
Nick Donfris

.RE
