import { analyzer, Analyzer } from '../src/analyze';
import { initializeParser } from '../src/parser';
import { workspaceManager } from '../src/utils/workspace-manager';
import { setLogger, createFakeLspDocument } from './helpers';
import { findReferenceSymbolType, ReferenceSymbolType } from '../src/parsing/reference-candidates';
import { getWordReferenceRegistry, WordReferenceRule } from '../src/parsing/word-references';
import { Option } from '../src/parsing/options';

setLogger();

const flags = (options: Option[]) => options.map(o => o.getAllFlags().join('/')).join(' ');

function describePosition(rule: WordReferenceRule): string {
  if ('option' in rule) return `value of \`${flags(rule.option)}\``;
  if ('match' in rule) return `match \`${rule.match.name}()\``;
  const at = rule.positional;
  if (at === 'all') return 'every argument';
  return 'at' in at ? `argument ${at.at}` : `arguments ${at.from}…`;
}

/** The merged registry as one markdown table, so a rule change reviews as one diff. */
function renderRegistry(): string {
  const lines = [
    '# Word references',
    '',
    'Generated by `tests/word-references.test.ts` from the `…WordReferences` rules in',
    '`src/parsing/*.ts`. Arguments are counted after skipping options and the values',
    'they consume. Any argument not listed here is literal text.',
    '',
    '| command | position | kind | when | unless |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const [command, rules] of [...getWordReferenceRegistry()].sort(([a], [b]) => a.localeCompare(b))) {
    for (const rule of rules.rules) {
      lines.push(`| \`${command}\` | ${describePosition(rule)}${rule.runsCommand ? ', runs it with the rest' : ''} | ${rule.kind} | ${rule.when ? `\`${flags(rule.when)}\`` : ''} | ${rule.unless ? `\`${flags(rule.unless)}\`` : ''} |`);
    }
    if (rules.stopAtDoubleDash) {
      lines.push(`| \`${command}\` | after \`--\` | _never_ | | |`);
    }
    if (rules.stopOptionsAtFirstArgument) {
      lines.push(`| \`${command}\` | options after argument 0 | _belong to argument 0_ | | |`);
    }
    if (rules.skipLeadingAssignments) {
      lines.push(`| \`${command}\` | leading \`NAME=value\` | _skipped_ | | |`);
    }
  }
  return lines.join('\n') + '\n';
}

describe('word-reference registry', () => {
  it('matches the reviewed rule table', async () => {
    await expect(renderRegistry()).toMatchFileSnapshot('__snapshots__/word-references.md');
  });

  // `Options.filter(o => o.equalsRawOption(…))` silently yields `[]` on a typo.
  it('every `option` rule names at least one flag', () => {
    for (const [command, rules] of getWordReferenceRegistry()) {
      for (const rule of rules.rules) {
        if ('option' in rule) expect(rule.option.length, `${command}: ${describePosition(rule)}`).toBeGreaterThan(0);
      }
    }
  });

  it('a flag value never maps to two kinds within one command', () => {
    for (const [command, rules] of getWordReferenceRegistry()) {
      const seen = new Map<string, ReferenceSymbolType>();
      for (const rule of rules.rules) {
        if (!('option' in rule)) continue;
        for (const flag of rule.option.flatMap(o => o.getAllFlags())) {
          const key = `${flag} when:${rule.when ? flags(rule.when) : ''} unless:${rule.unless ? flags(rule.unless) : ''}`;
          expect(seen.get(key) ?? rule.kind, `${command} ${flag}`).toBe(rule.kind);
          seen.set(key, rule.kind);
        }
      }
    }
  });
});

describe('findReferenceSymbolType() through the registry', () => {
  beforeEach(async () => {
    await initializeParser();
    await Analyzer.initialize();
  });
  afterEach(() => workspaceManager.clear());

  function classify(srcWithCaret: string): ReferenceSymbolType | null {
    const lines = srcWithCaret.split('\n');
    const line = lines.findIndex(l => l.includes('‸'));
    const character = lines[line]!.indexOf('‸');
    const doc = createFakeLspDocument('functions/word-refs.fish', srcWithCaret.replace('‸', ''));
    analyzer.analyze(doc);
    return findReferenceSymbolType(analyzer.nodeAtPoint(doc.uri, line, character)!);
  }

  it.each<[string, ReferenceSymbolType | null]>([
    // no rule: literal text
    ['echo ‸foo', null],
    ['printf "%s" ‸foo', null],
    ['some_cmd ‸foo', null],
    ['set x ‸foo', null],
    ['test ‸foo = bar', null],
    // positional: options and the values they consume are skipped
    ['bind -M insert ctrl-a ‸foo', 'function'],
    ['bind -M insert ‸ctrl-a foo', null],
    ['command ‸foo arg', 'function'],
    ['command foo ‸arg', null],
    ['command -v foo ‸bar', 'function'],
    ['builtin -q ‸foo', 'function'],
    ['builtin echo ‸foo', null],
    ['type -a ‸foo', 'function'],
    ['functions -q a ‸foo', 'function'],
    ['abbr -a --position anywhere gs ‸git status', 'function'],
    ['abbr -a --position anywhere ‸gs git status', null],
    // flags change the rule
    ['set -q a ‸foo', 'variable'],
    ['set -e ‸foo', 'variable'],
    // option values of each kind
    ['function f -w ‸foo; end', 'function'],
    ['function f -v ‸foo; end', 'variable'],
    ['function f -e ‸foo; end', 'emit'],
    ['function f -d ‸foo; end', null],
    ['complete -c x -l ‸foo', 'variable'],
    ['complete -c x -n ‸foo', 'function'],
    ['complete -c x -a ‸foo', null],
    ['some_cmd -w ‸foo', null],
    // `argparse … --` stops the rules
    ['argparse --name ‸foo h/help -- $argv', 'function'],
    ['argparse h/help -- ‸foo', null],
    ['argparse h/help -- (‸foo)', 'function'],
    ['emit ‸foo', 'emit'],
    ['emit foo ‸bar', null],
    // runners: option parsing stops at the command being run
    ['command ‸ls -a --sort time', 'function'],
    ['command ls -a --sort ‸time', null],
    ['exec ‸foo', 'function'],
    ['eval ‸foo bar', 'function'],
    ['eval foo ‸bar', null],
    ['time ‸foo', 'function'],
    ['nohup ‸foo arg', 'function'],
    ['nohup foo ‸arg', null],
    ['sudo -u root ‸foo -la', 'function'],
    ['sudo -u ‸root foo', null],
    ['sudo foo -u ‸x', null],
    ['doas -u root ‸foo', 'function'],
    ['env -u X FOO=1 ‸foo', 'function'],
    ['nice -n 10 ‸foo', 'function'],
    ['timeout -s KILL 5 ‸foo', 'function'],
    ['timeout ‸5 foo', null],
    ['xargs -n 1 ‸foo', 'function'],
    // nested runners: arguments after the run command follow its rules
    ['sudo env FOO=1 ‸foo', 'function'],
    ['sudo env FOO=1 foo ‸arg', null],
    ['command sudo -u root ‸foo', 'function'],
    ['time nice -n 5 ‸foo', 'function'],
    ['time nice -n ‸5 foo', null],
    ['xargs -n 1 sudo ‸foo', 'function'],
    ['sudo command echo ‸foo', null],
    ['sudo set -q ‸foo', 'variable'],
    ['sudo complete -c ‸foo', 'function'],
  ])('%s → %s', (src, kind) => {
    expect(classify(src)).toBe(kind);
  });
});
