#!/usr/bin/awk -f
#
# Post-process marked-man roff output to match fish's own man pages
# (e.g. `man string`, `man string-split`, generated by Sphinx). Transforms:
#
#   1. Synopsis blocks (the SYNOPSIS section and each subcommand's signature)
#      -> bold command/subcommand/flags, italic METAVARS, hand-authored no-fill
#      alignment preserved, and marked-man's `.RS` indent wrapper removed so the
#      signature sits at the standard man indent. A synopsis block is a fenced
#      block whose first line begins with `fish-lsp`.
#
#   2. Option entries -> `.TP` tagged paragraphs with the description forced onto
#      the next line (`.br`), so each flag (`-h`, `--help`) is a recognized,
#      hang-indented option and the description always sits below it.
#
#   3. Example code blocks get a leading blank line (`.sp`) and a constant-width
#      font (`.ft C` ... `.ft P`), keeping their `.RS` indent like `man string`.
#
# Uses only POSIX awk (user functions, gsub/`&`, getline), so it runs on mawk
# as well as gawk.

# `~~~` is an internal sentinel for the command name while flags are emphasized;
# it never appears in the source and is always restored before printing.
function emphasize(s,   after, n, word, tail) {
  gsub(/fish\\-lsp/, "~~~", s)                            # protect command name
  gsub(/[A-Z][A-Z]+/, "\\fI&\\fR", s)                     # METAVARS -> italic
  gsub(/(\\-)+[a-z]+((\\-)+[a-z]+)*/, "\\fB&\\fR", s)      # flags -> bold
  if (substr(s, 1, 3) == "~~~" && substr(s, 4, 1) == " ") {
    after = substr(s, 5)                                  # word after "fish-lsp "
    n = index(after, " ")
    word = (n > 0) ? substr(after, 1, n - 1) : after
    if (word ~ /^(start|env|info|url|complete)$/) {
      tail = (n > 0) ? substr(after, n) : ""
      s = "~~~ \\fB" word "\\fR" tail                      # subcommand -> bold
    }
  }
  gsub(/~~~/, "\\fBfish\\-lsp\\fR", s)                     # restore command, bold
  return s
}

# Drop GitHub backwards-compat anchors (e.g. <a id="start"></a>) so the stable
# `#start` URL fragments survive on GitHub without leaking into the man page.
/^<a [^>]*><\/a>$/ { next }

# --- .RS buffering: hold an .RS until we know whether it wraps a signature ----
/^\.SH / { if (pending_rs != "") { print pending_rs; pending_rs = "" } section = $2; print; next }
/^\.RS / { if (pending_rs != "") print pending_rs; pending_rs = $0; next }
/^\.RE$/ {
  if (drop_re) { drop_re = 0; next }            # .RE matching a dropped signature .RS
  if (pending_rs != "") { print pending_rs; pending_rs = "" }
  print; next
}

# --- block openers ------------------------------------------------------------
/^\.nf$/ {
  sig = 0; firstline = ""
  if (section == "SYNOPSIS") sig = 1
  else if ((getline firstline) > 0 && firstline ~ /^fish\\-lsp/) sig = 1
  if (sig) {
    if (pending_rs != "") { drop_re = 1; pending_rs = "" }   # drop wrapping .RS
    in_syn = 1
    print ".nf"
    if (firstline != "") print emphasize(firstline)
    next
  }
  if (pending_rs != "") { print pending_rs; pending_rs = "" }
  print ".sp"; print ".nf"; print ".ft C"; in_code = 1; drop_br = 0
  if (firstline == ".fi") { print ".ft P"; print ".fi"; in_code = 0 }
  else if (firstline != "") print firstline
  next
}

# Fallback: flush a buffered .RS before any other line is processed.
pending_rs != "" { print pending_rs; pending_rs = "" }

# --- synopsis block body: emphasize, preserve alignment -----------------------
in_syn {
  if ($0 == ".fi") { print ".fi"; in_syn = 0; next }
  print emphasize($0)
  next
}

# --- example code block body --------------------------------------------------
in_code {
  if ($0 == ".fi") { print ".ft P"; print ".fi"; in_code = 0; next }
  print
  next
}

# --- option entries -> .TP, description forced onto the next line -------------
/^\\fB\\-/ {
  line = $0
  if (match(line, /  +/)) {            # first run of 2+ spaces = tag/desc split
    tag  = substr(line, 1, RSTART - 1)
    desc = substr(line, RSTART + RLENGTH)
  } else {
    tag  = line
    desc = ""
  }
  print ".TP"
  print tag
  if (desc != "") { print ".br"; print desc }
  drop_br = 1                           # the .br that follows belongs to this entry
  next
}

# Drop the single trailing .br emitted after an option line (TP needs no break).
drop_br && /^\.br$/ { drop_br = 0; next }

{ drop_br = 0; print }
