#!/usr/bin/env node

const {execSync} = require('child_process');

function showHelp() {
  console.log([
    'USAGE: ./scripts/timestamp.js [OPTIONS]',
    '       yarn --silent run timestamp  [--latest | --nightly]',
    '',
    'OPTIONS:',
    '  -h, --help       Show this help message',
    '  -c, --complete   Output shell completion script (can be sourced by fish)',
    '      --latest     Get the latest publish time (default)',
    '      --nightly    Get the nightly publish time',
    '',
    "EXAMPLES:",
    "  # Get the `fish-lsp@latest` published timestamp",
    "  >_ ./scripts/timestamp.js --latest",
    "",
    "  # Get the `fish-lsp@nightly` published timestamp",
    "  >_ ./scripts/timestamp.js --nightly",
    "",
    "  # Use the latest publish timestamp for reproducible builds",
    "  >_ SOURCE_DATE_EPOCH=(./scripts/timestamp.js) yarn build:npm &>/dev/null",
    "  >_ and ./dist/fish-lsp --build-time ",
    "  # Matches `fish-lsp@latest` published time",
    "",
    "  # If we build the source code again, without exporting SOURCE_DATE_EPOCH,",
    "  # the build time embedded in the binary will be overwritten with the current time.",
    "  >_ yarn build:npm &>/dev/null",
    "  >_ and ./dist/fish-lsp --build-time",
    "  # Shows current time, which is different from `fish-lsp@latest` published time.",
    "",
    "  # To get the completions in your fish shell session, run:",
    "  >_ ./scripts/timestamp.js --complete | source",
  ].join('\n'));
  process.exit(0);
}

function getCompletions() {
  const script = require('path').resolve(__filename);
  const completions = [
    ['--latest', 'Get publish timestamp from `fish-lsp@latest` tag'],
    ['--nightly', 'Get publish timestamp from `fish-lsp@nightly` tag'],
    ['-h', 'Show help message'],
    ['--help', 'Show help message'],
    ['-c', 'Output shell completion script'],
    ['--complete', 'Output shell completion script'],
  ].map(([flag, desc]) => [flag, `'${desc}'`].join('\\t')).join('\n');

  console.log([
    '# fish shell completions for ./scripts/timestamp.js',
    '# Generated by ./scripts/timestamp.js --complete',
    `complete --path ${script} -f`,
    `complete --path ${script} -n '__fish_use_subcommand' -k -xa "${completions}"`,
    `# yarn run timestamp`,
    `complete -c yarn -n '__fish_seen_subcommand_from timestamp' -f`,
    `complete -c yarn -n '__fish_seen_subcommand_from timestamp' -l latest -d 'Get the latest publish time'`,
    `complete -c yarn -n '__fish_seen_subcommand_from timestamp' -l nightly -d 'Get the nightly publish time'`,
    `complete -c yarn -n '__fish_seen_subcommand_from timestamp' -s h -l help -d 'Show help message'`,
    `complete -c yarn -n '__fish_seen_subcommand_from timestamp' -s c -l complete -d 'Output shell completion script' | string trim -l`].join('\n'));
  process.exit(0);
}

function getPublishTimestamp(identifier) {
  try {
    // Get version
    const versionCmd = `npm show ${identifier} version --json`;
    const version = execSync(versionCmd, {encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore']}).trim().replace(/^"|"$/g, '');

    // Get time object
    const timeCmd = `npm show ${identifier} time --json`;
    const timeJson = execSync(timeCmd, {encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore']});
    const timeData = JSON.parse(timeJson);

    // Get the specific version's publish time
    const utcTimestamp = timeData[version];

    if (!utcTimestamp) {
      process.exit(1);
    }

    // Convert to Unix timestamp (seconds since epoch)
    const unixTimestamp = Math.floor(new Date(utcTimestamp).getTime() / 1000);
    console.log(unixTimestamp);
  } catch (error) {
    process.exit(1);
  }
}

// Parse arguments
const args = process.argv.slice(2);

if (args.includes('-h') || args.includes('--help')) {
  showHelp();
}

if (args.includes('-c') || args.includes('--complete')) {
  getCompletions();
}

// Determine identifier based on flags
const identifier = args.includes('--nightly') ? 'fish-lsp@nightly' : 'fish-lsp@latest';

getPublishTimestamp(identifier);
