#!/usr/bin/env fish

not command -aq npx
and echo "Missing 'npx' requirement" >&2
and return 1

not command -aq yarn
and echo "Missing 'yarn' requirement" >&2
and return 1

not command -aq yarn-audit-fix
and echo "Missing 'yarn-audit-fix' requirement" >&2
and return 1

function run_upgrade_script
    function show_command_and_eval
        echo "$(set_color blue)>_$(set_color --italics green) $argv $(set_color normal)"
        eval $argv 2>/dev/null
    end

    show_command_and_eval npx npm-check-updates --target minor -u --reject web-tree-sitter,memfs,eslint
    and show_command_and_eval yarn install
    and show_command_and_eval yarn build
    and show_command_and_eval yarn-audit-fix
    or {
      echo "$(set_color red)upgrade script stopped...exiting!$(set_color normal)"
      return 1
    }

    return 0
end

run_upgrade_script
