# auto generated by fish-lsp
complete -c git_branch_exists -f
complete -c git_branch_exists -l fallback -xa 'master main trunk dev' -d 'branch to fallback to if none of the branches exist'
complete -c git_branch_exists -s h -l help -d 'show help for this command'
complete -c git_branch_exists -xa '(git branch -a --format=\'%(refname:short)\')'
